config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :file_assets

  resources :posts, :param => :slug
  resources :categories, :param => :slug

  root to: redirect('/ideas')

  resources :categories, :param => :slug, :path => '', :only => [:show], :as => 'category_clean' do
    resources :posts, :param => :slug, :path => '', :only => [:show]
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  has_many :file_assets
  default_scope { order('published_at DESC, title DESC') }

  before_validation :create_slug
  validates :title, presence: true, allow_blank: false
  validates :slug, presence: true, allow_blank: false, uniqueness: true

  def image_assets
    return self.file_assets.select{ |f| f.is_image? }
  end

  def root_category
    cat = self.category
    while not cat.parent_id.nil?
      cat = cat.parent
    end
    return cat
  end

  def next
    current = nil
    category.posts.where('published_at >= ?', published_at).each do |p|
      if p.id == id then break else current = p end
    end
    return current
  end

  def previous
    current = nil
    category.posts.where('published_at <= ?', published_at).reverse.each do |p|
      if p.id == id then break else current = p end
    end
    return current
  end

  def to_param
    return slug
  end

  def create_slug
    self.slug = self.title.to_s.parameterize
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :authenticate_admin!, :only => [:show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
    if @post.nil?
      render Category.find_by(slug: params[:slug])
    end
  end

  # GET /posts/new
  def new
    @categories = Category.all
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @categories = Category.all
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      @categories = Category.all
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      @categories = Category.all
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by(slug: params[:slug])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:category_id, :body, :title, :is_single_image, :published_at)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_display_post.html.erb
<% if not defined? title_link then title_link = true end %>
<div class="post-card">
  <% if post.is_single_image and post.image_assets.size > 0 %>
    <img src="<%= dev_safe_url(post.image_assets.first.content.url) %>" />
  <% end %>

  <div class="post-body">
    <% if title_link %>
      <%= link_to category_clean_post_path(post.category, post) do %>
        <h1>
          <%= post.title %>
        </h1>
      <% end %>
    <% else %>
      <h1>
        <%= post.title %>
      </h1>
    <% end %>

    <% if post.root_category.name.downcase == BLOG_CATEGORY_NAME.downcase %>
      <div class="published-at">
        Published on <%= post.published_at.strftime("%B %d, %Y") %>
      </div>
    <% end %>

    <% if post.body != post.title %>
      <% if post.is_single_image %>
        <div class="caption"><%=raw post.body %></div>
      <% else %>
        <%=raw post.body %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, rows: 12, cols: 72 %>
  </div>
  <div class="field">
    <%= render partial: "shared/category_picker", locals: {f: f, property: :category_id} %>
  </div>
  <div class="field">
    <%= f.label :is_single_image %><br>
    <%= f.check_box :is_single_image %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="field">
    <% @post.file_assets.each do |asset| %>
      <div class="asset-info"><%= asset.name %>: <%= asset.content.url %></div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="post-card">
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="post-card">
<h1>All posts</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Title</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% Category.walk_tree do |cat, level| %>
      <% if cat.posts.empty? %>
        <tr>
          <td><%= "#{'- '*level}#{cat.name}" %></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>
      <% cat.posts.each do |post| %>
        <tr>
          <td><%= "#{'-  '*level}#{cat.name}" %></td>
          <td><%= link_to post.title, post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
        </tr>
      <% end %>
    <% end %>
    <% @posts.each do |post| %>
      <% if post.category.nil? %>
        <tr>
          <td>Uncategorized</td>
          <td><%= link_to post.title, post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="post-card">
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<%= render partial: "posts/display_post", locals: {post: @post, title_link: false} %>
<% next_post = @post.next
previous_post = @post.previous
unless next_post.nil? and previous_post.nil? %>
  <div class="proximal-buttons bar">
    <% if previous_post.nil? %>
      <div class="previous empty"></div>
    <% else %>
      <%= link_to previous_post do %>
        <div class="previous">
          &laquo; Previous<br> <%= previous_post.title %>
          <div class="border-line"></div>
        </div>
      <% end %>
    <% end %>
    <div class="keyboard-tip">
      Navigate with left and right arrow keys!
    </div>
    <% if next_post.nil? %>
      <div class="next empty"></div>
    <% else %>
      <%= link_to next_post do %>
        <div class="next">
          <div class="border-line"></div>
          Next &raquo;<br> <%= next_post.title %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>