config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :file_assets

  resources :posts, :param => :slug
  resources :categories, :param => :slug

  root to: redirect('/ideas')

  resources :categories, :param => :slug, :path => '', :only => [:show], :as => 'category_clean' do
    resources :posts, :param => :slug, :path => '', :only => [:show]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend ActsAsTree::TreeWalker

  acts_as_tree order: "name"
  has_many :posts
  before_validation :create_slug

  validates :name, presence: true, allow_blank: false
  validates :slug, presence: true, allow_blank: false, uniqueness: true
  validate :no_loops

  def ancestry
    out, current = [self.name], self
    while not current.parent.nil?
      out << current.parent.name
      current = current.parent
    end
    return out.reverse.join(" - ")
  end

  def to_param
    return slug
  end

  def create_slug
    self.slug = self.name.to_s.parameterize
  end

  private

  def no_loops
    max_depth, current_depth, current = 500, 0, self
    seen = []
    (0...max_depth).each do |depth|
      if current.nil? then return end
      if seen.include? current.id
        errors.add(:parent_id, "creates a loop after traversing #{depth} times up the tree.")
        return
      end
      seen << current.id
      current = current.parent
    end
    errors.add(:parent_id, "did not reach a root node within #{max_depth} traversals up the tree.")
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_admin!, :only => [:show]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
    raise ActiveRecord::RecordNotFound if @category.blank?
    if @category.posts.size == 1
      @post = @category.posts.first
      render "posts/show"
    end
  end

  # GET /categories/new
  def new
    @categories = Category.all
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @categories = Category.all
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_clean_path(@category), notice: 'Category was successfully created.'
    else
      @categories = Category.all
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      @categories = Category.all
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find_by(slug: params[:slug])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name, :parent_id, :is_visual)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper

  def color_from_string query
    return '#'+query.hash.to_s(16).slice(1,6)
  end

end

app/views/categories/_category_category_tile.html.erb
<% 
bg = "background-color: #{color_from_string(category.name)}; "
category.posts.each do |post|
  if post.image_assets.size > 0
    bg << "background-image: url(#{dev_safe_url(post.image_assets.first.content.url(:preview))})"
    break
  end
end %>
<%= link_to category_clean_path(category) do %>
  <div class="category-tile <%= cycle("left-side", "right-side") %>" style="<%= bg || "" %>">
    <div class="tile-title">
      <%= category.name %>
    </div>
  </div>
<% end %>

app/views/categories/_category_tile.html.erb
<% 
if post.file_assets.size > 0
  bg = "background-image: url(#{dev_safe_url(post.file_assets.first.content.url)})"
else
  bg = "background-color: #{color_from_string(post.title)}"
end %>
<%= link_to post_path(post) do %>
  <div class="category-tile <%= cycle("left-side", "right-side") %>" style="<%= bg %>">
    <div class="tile-title">
      <%= post.title %>
    </div>
  </div>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :is_visual %><br>
    <%= f.check_box :is_visual %>
  </div>
  <div class="field">
    <%= render partial: "shared/category_picker", locals: {f: f, property: :parent_id} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_post_category_bar.html.erb
<%= link_to category_clean_post_path(post.category, post) do %>
  <div class="bar">
    <div class="liner">
      <%= post.title %>
    </div>
  </div>
<% end %>

app/views/categories/_post_category_tile.html.erb
<% 
bg = "background-color: #{color_from_string(post.title)};"
if post.image_assets.size > 0
  bg << "background-image: url(#{dev_safe_url(post.image_assets.first.content.url(:preview))});"
end %>
<%= link_to category_clean_post_path(post.category, post) do %>
  <div class="tile" style="<%= bg %>">
    <div class="tile-title">
      <%= post.title %>
    </div>
    <div class="hover-border"></div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %> |
<%= link_to 'Destroy', @category, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/categories/index.html.erb
<div class="post-card">
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>
</div>

app/views/categories/new.html.erb
<div class="post-card">
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<div class="bar">
  <div class="liner">
    <%= @category.ancestry %>
  </div>
</div>

<%
if @category.is_visual
  partial = "post_category_tile" 
else
  partial = "posts/display_post"
end
%>

<% if @category.posts.size > 0 %>
  <% @category.posts.sort_by(&:published_at).reverse.each do |post| %>
    <%= render partial: partial, locals: {post: post} %>
  <% end %>
<% else %>
  <% @category.children.map(&:posts).flatten.sort_by(&:published_at).reverse.each do |post| %>
    <%= render partial: partial, locals: {post: post} %>
  <% end %>
<% end %>