config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :file_assets

  resources :posts, :param => :slug
  resources :categories, :param => :slug

  root to: redirect('/ideas')

  resources :categories, :param => :slug, :path => '', :only => [:show], :as => 'category_clean' do
    resources :posts, :param => :slug, :path => '', :only => [:show]
  end

end

app/models/file_asset.rb
class FileAsset < ActiveRecord::Base
  belongs_to :post

  has_attached_file :content, {
    styles: {
      preview: '920x1160^'
    },
    convert_options: {
      preview: '-gravity Center -crop 460x580+0+0 -strip'
    }
  }.merge(PAPERCLIP_FILE_ASSET_STORAGE_OPTIONS)

  before_post_process :is_image?

  validates_attachment_presence :content
  validates_attachment_size :content, :less_than => 200.megabytes

  validates :name, presence: true
  validates :post, presence: true

  # it's only me that's using the admin, so I want to be able to upload arbitrary files
  do_not_validate_attachment_file_type :content

  def is_image?
    image_types = ["image/tiff", "image/jpeg", "image/jpg", "image/png", "image/x-png", "image/gif"]
    return image_types.include?(self.content_content_type)
  end

end

app/controllers/file_assets_controller.rb
class FileAssetsController < ApplicationController
  before_action :set_file_asset, only: [:show, :edit, :update, :destroy]

  # GET /file_assets
  def index
    @file_assets = FileAsset.all
  end

  # GET /file_assets/1
  def show
  end

  # GET /file_assets/new
  def new
    @posts = Post.all
    @file_asset = FileAsset.new
  end

  # GET /file_assets/1/edit
  def edit
    @posts = Post.all
  end

  # POST /file_assets
  def create
    @file_asset = FileAsset.new(file_asset_params)

    if @file_asset.save
      redirect_to @file_asset, notice: 'File asset was successfully created.'
    else
      @posts = Post.all
      render :new
    end
  end

  # PATCH/PUT /file_assets/1
  def update
    if @file_asset.update(file_asset_params)
      redirect_to @file_asset, notice: 'File asset was successfully updated.'
    else
      @posts = Post.all
      render :edit
    end
  end

  # DELETE /file_assets/1
  def destroy
    @file_asset.destroy
    redirect_to file_assets_url, notice: 'File asset was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_asset
      @file_asset = FileAsset.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def file_asset_params
      params.require(:file_asset).permit(:name, :content, :post_id)
    end
end

app/helpers/file_assets_helper.rb
module FileAssetsHelper
end

app/views/file_assets/_form.html.erb
<%= form_for(@file_asset) do |f| %>
  <% if @file_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_asset.errors.count, "error") %> prohibited this file_asset from being saved:</h2>

      <ul>
      <% @file_asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.file_field :content %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.collection_select :post_id, @posts, :id, :title, prompt: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_assets/edit.html.erb
<h1>Editing file_asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_asset %> |
<%= link_to 'Back', file_assets_path %>

app/views/file_assets/index.html.erb
<h1>Listing file_assets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @file_assets.each do |file_asset| %>
      <tr>
        <td><%= file_asset.name %></td>
        <td><%= file_asset.content %></td>
        <td><%= link_to file_asset.post.title, edit_post_path(file_asset.post) %></td>
        <td><%= link_to 'Show', file_asset %></td>
        <td><%= link_to 'Edit', edit_file_asset_path(file_asset) %></td>
        <td><%= link_to 'Destroy', file_asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File asset', new_file_asset_path %>

app/views/file_assets/new.html.erb
<h1>New file_asset</h1>

<%= render 'form' %>

<%= link_to 'Back', file_assets_path %>

app/views/file_assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @file_asset.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @file_asset.content %>
</p>

<p>
  <strong>Post:</strong>
  <%= @file_asset.post.title %>
</p>

<%= link_to 'Edit', edit_file_asset_path(@file_asset) %> |
<%= link_to 'Back', file_assets_path %>