config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :file_assets

  resources :posts, :param => :slug
  resources :categories, :param => :slug

  root to: redirect('/ideas')

  resources :categories, :param => :slug, :path => '', :only => [:show], :as => 'category_clean' do
    resources :posts, :param => :slug, :path => '', :only => [:show]
  end

end

app/views/layouts/_admin_nav.html.erb
<% nav = {
  "Categories" => {
    "All" => categories_path,
    "New" => new_category_path
  },
  "Posts" => {
    "All" => posts_path,
    "New" => new_post_path
  },
  "File uploads" => {
    "All" => file_assets_path,
    "New" => new_file_asset_path
  },
  "User" => {
    "Log out" => destroy_admin_session_path
  }
}
nav.each_pair do |name, subtree| %>
  <div class="nav-toggled-off togglable menu-category category-level-0"><%= name %></div>
  <% subtree.each_pair do |action, target| %>
    <%= link_to target do %>
      <div class="nav-toggled-off togglable menu-category category-level-1">
        <%= action %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon/favicon-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon/favicon-160x160.png" sizes="160x160">
<link rel="icon" type="image/png" href="/favicon/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon/favicon-16x16.png" sizes="16x16">
<link rel="icon" type="image/png" href="/favicon/favicon-32x32.png" sizes="32x32">
<meta name="msapplication-TileColor" content="#00aba9">
<meta name="msapplication-TileImage" content="/favicon/mstile-144x144.png">

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-15328016-4', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>
<% if flash.count > 0 %>
  <script>
    $('.close').on('click', function(){
      $(this).parent('.alert').remove();
    });
  </script>
<% end %>

app/views/layouts/_public_nav.html.erb
<div class="menu-category mini-bar toggle-nav">
  <div class="liner">
    Show Navigation
  </div>
</div>
<% Category.includes(:children).where(parent_id: nil).each do |top_category| %>
  <%= link_to category_clean_path(top_category) do %>
    <div class="nav-toggled-off togglable menu-category mini-bar">
      <div class="liner">
        <%= top_category.name %>
      </div>
      <% if top_category.children.size > 1 %>
        <div class="subpanel">
          <% top_category.children.each do |child_category| %>
            <%= link_to category_clean_path(child_category) do %>
              <div class="subpanel-row">
                <%= child_category.name %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%- title = (defined? @post) ? @post.title : "Neal Donnelly dot com" %>
  <title><%= title %></title>
  <meta property="og:title" content="<%= title %>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/favicon" %>
  <%= render "layouts/google_analytics" %>
</head>
<body>

<div class="color-overlay"></div>

<div class="grid-container">
  <div class="nav">
    <%= render "layouts/public_nav" %>
    <% if current_admin %>
      <%#= render "layouts/admin_nav" %>
    <% end %>
  </div>
  <!-- <div class="main"> -->
    <%= render 'layouts/messages' %>
    <div class="primary-content">
      <%= yield %>
    </div>
  <!-- </div> -->

</div>

</body>
</html>